name: 功能建议 / Feature request
description: 告诉我们你想怎样学习 / Suggest an improvement
title: "[Feature] "
body:
  - type: textarea
    id: problem
    attributes:
      label: 想解决的问题 / What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: 你的建议 / Your suggestion
    validations:
      required: true
