import AnimatedDetails from './AnimatedDetails'
import { BookOpenCheck, CircleAlert, Download, LoaderCircle, Save, Sparkles, Upload, X, Bot, RefreshCw } from 'lucide-react'
import { modelChoices, modelLabel } from '../lib/modelChoices.mjs'
import { DEFAULT_READING_PREFERENCES } from '../lib/readingPreferences.mjs'

export default function SettingsDialog({ state, actions }) {
  const { settingsTab, modelsRefreshing, readingPreferences, readingStyle, aiSettingsBusy, systemReducedMotion, motionPreview,
    aiSettings, aiModels, showAllModels, modelSearch, dictionaryStatus, aiSettingsError, updateStatus } = state
  const { close, setSettingsTab, setReadingPreferences, setReadingStyle, setMotionPreview, selectAiProvider, setAiSettings,
    selectSavedKey, deleteSavedKey, selectDiscoveredModel, refreshAiModels, setShowAllModels, setModelSearch,
    runDictionaryAction, saveAiConfiguration, runUpdateAction } = actions
  return <div className="backup-backdrop" role="presentation" onClick={close}>
    <form className="backup-dialog ai-settings-dialog" data-settings-tab={settingsTab} onSubmit={saveAiConfiguration} onClick={event => event.stopPropagation()}>
      <button className="backup-close" type="button" onClick={close} aria-label="关闭设置"><X size={18} /></button>
      <p className="eyebrow">APPLICATION SETTINGS</p><h2>设置</h2>
      <nav className="settings-tabs" aria-label="设置分类">{[['ai', 'AI 与模型'], ['dictionary', '本地词典'], ['appearance', '阅读与动效'], ['updates', '关于与更新']].map(([id, label]) => <button key={id} type="button" aria-pressed={settingsTab === id} onClick={() => setSettingsTab(id)}>{label}</button>)}</nav>
      {modelsRefreshing && <p className="settings-refresh-status" role="status"><LoaderCircle className="spin" size={14} /> 正在刷新模型目录…</p>}
      <section className="settings-section reading-settings"><div className="settings-section-heading"><b>阅读与字号</b><button type="button" onClick={() => setReadingPreferences(DEFAULT_READING_PREFERENCES)}>恢复默认</button></div><label>读音显示方式<select value={readingStyle} onChange={event => setReadingStyle(event.target.value)}><option value="hiragana">平假名</option><option value="romaji">罗马音</option></select></label><label>界面字号 · {readingPreferences.interfaceSize}px<input type="range" min="16" max="24" step="1" value={readingPreferences.interfaceSize} onChange={event => setReadingPreferences({ ...readingPreferences, interfaceSize: Number(event.target.value) })} /></label><label>歌词字号 · {readingPreferences.lyricSize}px<input type="range" min="24" max="40" step="1" value={readingPreferences.lyricSize} onChange={event => setReadingPreferences({ ...readingPreferences, lyricSize: Number(event.target.value) })} /></label><p>调整后自动保存。</p></section>
      {aiSettingsBusy === 'load' && <p><LoaderCircle className="spin" size={14} /> 正在读取本机设置…</p>}
      <section className="settings-section"><label>动态效果<select value={readingPreferences.motion} onChange={event => setReadingPreferences({ ...readingPreferences, motion: event.target.value })}><option value="on">开启</option><option value="system">跟随系统</option><option value="off">关闭</option></select></label><p className="field-help">系统减少动态效果：{systemReducedMotion ? '已开启' : '未开启'}。选择“开启”会使用应用动画，不跟随系统禁用。</p><button type="button" onClick={() => setMotionPreview(value => value + 1)}>播放动效预览</button><div className="motion-demo" aria-label="动画预览"><span key={motionPreview}>UTA</span></div></section>
      <section className="settings-section update-settings" aria-label="应用更新"><div className="settings-section-heading"><div><RefreshCw size={17} /><b>版本与更新</b></div><span>当前版本 {updateStatus?.currentVersion || '读取中'}</span></div>
        <p className="field-help">构建时间：{new Date(__UTA_BUILD_TIME__).toLocaleString('zh-CN')}</p>
        <p className="update-status" role="status">{updateStatus?.phase === 'checking' ? '正在检查新版本…' : updateStatus?.phase === 'available' ? `发现新版本 ${updateStatus.availableVersion}` : updateStatus?.phase === 'downloading' ? `正在下载 ${updateStatus.availableVersion}：${updateStatus.progress}%` : updateStatus?.phase === 'downloaded' ? `版本 ${updateStatus.availableVersion} 已下载，重启后安装。` : updateStatus?.phase === 'current' ? '当前已是最新发布版本。' : updateStatus?.phase === 'error' ? '检查或下载未完成，可稍后重试。' : updateStatus?.phase === 'unsupported' ? updateStatus.message : '启动后会自动检查 GitHub Release，也可手动检查。'}</p>
        {updateStatus?.phase === 'downloading' && <div className="update-progress" role="progressbar" aria-label="更新下载进度" aria-valuenow={updateStatus.progress} aria-valuemin="0" aria-valuemax="100"><span style={{ width: `${updateStatus.progress}%` }} /></div>}
        {updateStatus?.phase === 'error' && <p className="settings-inline-error"><CircleAlert size={15} /> {updateStatus.message}</p>}
        <div className="settings-dictionary-actions"><button type="button" onClick={() => runUpdateAction('check')} disabled={!updateStatus || ['checking', 'downloading', 'downloaded', 'unsupported'].includes(updateStatus.phase)}>检查更新</button>{updateStatus?.phase === 'available' && <button type="button" onClick={() => runUpdateAction('download')}>下载新版本</button>}{updateStatus?.phase === 'downloaded' && <button type="button" onClick={() => runUpdateAction('install')}>重启并安装</button>}<a href="https://github.com/CosmerHomura/Japanese-song-learning-website/releases" target="_blank" rel="noreferrer">查看发布页</a></div>

      </section>
      {aiSettings && <div className="ai-settings-fields">
        <section className="settings-section"><div className="settings-section-heading"><div><Bot size={16} /><b>AI 供应商与模型</b></div><span>选厂家即可浏览模型</span></div>
          <label><span className="settings-step-label">1 · 选择供应商</span><select value={aiSettings.provider} onChange={event => selectAiProvider(event.target.value)}>{(aiSettings.providers || []).map(provider => <option key={provider.id} value={provider.id}>{provider.label}</option>)}</select></label>
          {aiSettings.provider === 'custom' && <label><span className="settings-step-label">自定义接口地址</span><input type="url" value={aiSettings.base_url} onChange={event => setAiSettings({ ...aiSettings, base_url: event.target.value })} /><small className="field-help">仅自定义 OpenAI 兼容服务需要填写，普通厂家地址由应用维护。</small></label>}
          <section className="key-management">{(aiSettings.keys || []).some(key => key.provider === aiSettings.provider) && <><label>已保存的 Key<select value={aiSettings.selected_key_id || ''} onChange={event => selectSavedKey(event.target.value)}><option value="">添加新 Key / 暂不使用</option>{(aiSettings.keys || []).filter(key => key.provider === aiSettings.provider).map(key => <option key={key.id} value={key.id}>{key.name} · ••••{key.last_four}</option>)}</select></label>{aiSettings.selected_key_id && <button type="button" onClick={deleteSavedKey} disabled={Boolean(aiSettingsBusy)}>删除此 Key</button>}</>}<label>{aiSettings.selected_key_id ? '添加其他 Key（可选）' : 'API Key'}<input type="password" value={aiSettings.api_key || ''} onChange={event => setAiSettings({ ...aiSettings, api_key: event.target.value, key_name: '' })} placeholder={aiSettings.selected_key_id ? '留空继续使用已保存的 Key' : '粘贴 Key 即可，无需命名'} autoComplete="off" /></label><small className="field-help">保存在本机并加密；不填 Key 也可以浏览模型。</small></section>
          <div className="ai-model-row"><label><span className="settings-step-label">模型</span><select value={aiSettings.model} onChange={event => selectDiscoveredModel(event.target.value)}>{!modelChoices(aiModels, aiSettings.model, showAllModels, modelSearch).some(model => model.id === aiSettings.model) && <option value={aiSettings.model}>{modelLabel(aiModels.find(model => model.id === aiSettings.model) || { id: aiSettings.model || '正在读取模型…' })}</option>}{modelChoices(aiModels, aiSettings.model, showAllModels, modelSearch).map(model => <option key={model.id} value={model.id}>{modelLabel(model)}</option>)}</select></label><button type="button" onClick={() => refreshAiModels()} disabled={modelsRefreshing || Boolean(aiSettingsBusy)}>{modelsRefreshing ? <LoaderCircle className="spin" size={13} /> : <Sparkles size={13} />} 刷新</button></div>
          <div className="model-list-options"><button type="button" onClick={() => { setShowAllModels(!showAllModels); setModelSearch('') }}>{showAllModels ? '收起全部模型' : `全部模型（${aiModels.length}）`}</button>{showAllModels && <input type="search" aria-label="搜索模型" placeholder="搜索名称或接口 ID" value={modelSearch} onChange={event => setModelSearch(event.target.value)} />}</div>
          <AnimatedDetails className="model-technical-details" title={<>价格与连接详情</>}><p className="ai-settings-note">接口 ID：{aiSettings.model} · {aiSettings.base_url}</p>
          <p className="ai-settings-note">{aiModels[0]?.model_source || '公开模型目录'} · {aiModels[0]?.account_verified ? '已核对账号权限' : '公开目录供浏览，实际可用性需用 Key 校验'}。最新读取：{aiModels[0]?.catalog_checked_at ? new Date(aiModels[0].catalog_checked_at).toLocaleString() : '尚未读取'}。</p>
          <dl className="ai-price-summary"><div><dt>输入 / 百万 token</dt><dd>¥ {aiSettings.pricing_source === '供应商未提供' ? '暂未获取' : Number(aiSettings.input_price || 0).toFixed(4)}</dd></div><div><dt>缓存输入 / 百万 token</dt><dd>¥ {Number(aiSettings.cached_input_price || 0).toFixed(4)}</dd></div><div><dt>输出 / 百万 token</dt><dd>¥ {aiSettings.pricing_source === '供应商未提供' ? '暂未获取' : Number(aiSettings.output_price || 0).toFixed(4)}</dd></div><div><dt>价格来源</dt><dd>{aiSettings.pricing_source || '供应商未提供'}</dd></div></dl>
          <p className="ai-settings-note">人民币费用为本机估算，便于比较每首歌的成本；最终扣费以供应商账单为准。</p>
          </AnimatedDetails>
        </section>
        <section className="settings-section"><div className="settings-section-heading"><div><BookOpenCheck size={16} /><b>本地词典</b></div><span>{dictionaryStatus?.installed ? '已安装' : '未安装（可选）'}</span></div>
          <p className="ai-settings-note">这是可选增强项：不安装仍可用 SudachiPy 自动注音；安装后可显示更多日中词义。推荐自动下载 Tomoshi Dictionary Open Data Layer，网络不稳定时也可打开发布页手动下载。</p>
          <p className="dictionary-format-hint"><b>上传格式：</b>.db.zst、.db、.sqlite、.sqlite3；SQLite 必须包含 entries、forms、zh_defs 表。</p>
          {dictionaryStatus?.error && <p className="settings-inline-error"><CircleAlert size={13} /> {dictionaryStatus.error}</p>}
          {dictionaryStatus && ['downloading', 'installing', 'cancelling'].includes(dictionaryStatus.phase) && <><div className="dictionary-progress"><span style={{ width: dictionaryStatus.total_bytes ? `${Math.min(100, dictionaryStatus.downloaded_bytes / dictionaryStatus.total_bytes * 100)}%` : dictionaryStatus.phase === 'installing' ? '100%' : '18%' }} /></div><div className="dictionary-progress-meta"><span>{dictionaryStatus.phase === 'installing' ? '正在校验并安装' : '正在下载推荐词典'}</span>{dictionaryStatus.total_bytes && <b>{Math.round(dictionaryStatus.downloaded_bytes / dictionaryStatus.total_bytes * 100)}%</b>}</div></>}
          <div className="settings-dictionary-actions">{dictionaryStatus && ['downloading', 'installing'].includes(dictionaryStatus.phase) ? <button type="button" className="danger" onClick={() => runDictionaryAction('cancel')}>取消下载</button> : <><button type="button" onClick={() => runDictionaryAction('download')}><Download size={12} /> {dictionaryStatus?.phase === 'cancelled' ? '继续下载' : '下载推荐词典'}</button><button type="button" onClick={() => runDictionaryAction('chooseLocal')}><Upload size={12} /> 上传本地词典</button><button type="button" onClick={() => window.utaDesktop?.dictionary?.openReleases()}>打开发布页</button></>}</div>
        </section>
      </div>}
      {aiSettingsError && <p className="library-backup-error" role="alert"><CircleAlert size={14} /> {aiSettingsError}</p>}
      <div className="backup-dialog-actions"><button type="button" onClick={close}>关闭</button>{settingsTab === 'ai' && <button type="submit" disabled={!aiSettings || Boolean(aiSettingsBusy)}>{aiSettingsBusy === 'save' ? <LoaderCircle className="spin" size={14} /> : <Save size={14} />} 保存 AI 设置</button>}</div>
    </form>
  </div>
}
